# Generated by Django 3.2 on 2022-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('state', models.SmallIntegerField()),
            ],
            options={
                'permissions': [('can_execute_query', 'Can Execute Query')],
            },
        ),
    ]
