# Generated by Django 4.2 on 2024-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlconsole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylog',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='querylog',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'Success'), (2, 'Error')]),
        ),
    ]
